global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: "walter-ai"
    static_configs:
      - targets: ["walter-api:8000"]
    metrics_path: /metrics
