"""
Data schema definitions (Pydantic models).
This module defines the structure of request and response objects
to ensure type validation and data consistency.
"""

from pydantic import BaseModel, Field
from typing import List, Optional

class ChatMessage(BaseModel):
    """
    Represents an individual message within a conversation.
    
    Attributes:
        role: The role of the sender ("user" or "assistant").
        content: The textual content of the message.
    """
    role: str # "user" or "assistant"
    content: str

class ChatRequest(BaseModel):
    """
    Schema for the chat request sent by the client.
    """
    query: Optional[str] = Field(None, min_length=1, max_length=500, description="User question or command")
    session_id: Optional[str] = Field(None, description="Unique ID for conversation thread and persistence")
    action: Optional[str] = Field("chat", description="Action to perform: 'init' for greeting or 'chat' for normal interaction")
    history: Optional[List[ChatMessage]] = Field([], description="Previous conversation history to provide context to the model")

class ChatResponse(BaseModel):
    """
    Schema for the response returned by the system.
    """
    response: str = Field(..., description="Response generated by WALTER_AI's neural core")
